In [ ]:
/usr/spark-2.0.0/spark-streaming-kafka-0-8-assembly_2.11-2.2.1.jar'print sc

In [1]:
from pyspark.sql import Row
def parse(x):
    if ('user' in x): 
        return Row(username=x['user']['screen_name'], count=1, created_at=x['created_at'])
    else:
        return []

In [2]:

import os, json
#os.environ['PYSPARK_SUBMIT_ARGS'] = '--jars /usr/spark-2.0.0/spark-streaming-kafka-0-8-assembly_2.11-2.2.1.jar'

from pyspark.streaming import StreamingContext
from pyspark.streaming.kafka import KafkaUtils

# Lazily instantiated global instance of SparkSession
def getSparkSessionInstance(sparkConf):
    if ("sparkSessionSingletonInstance" not in globals()):
        globals()["sparkSessionSingletonInstance"] = SparkSession \
            .builder \
            .config(conf=sparkConf) \
            .getOrCreate()
    return globals()["sparkSessionSingletonInstance"]

def process(time, rdd):
    spark = getSparkSessionInstance(rdd.context.getConf())
        
    df = spark.createDataFrame(rdd)
    df.show()





ssc = StreamingContext(sc, 1)

kafkaStream = KafkaUtils.createStream(ssc, 'kafka:2181', 'Spark', {'twitter-stream':1})

parsed = kafkaStream.map(lambda v: json.loads(v[1]))
parsed.count().map(lambda x:'Tweets in this batch: %s' % x).filter(lambda x: len(x>0)).pprint()
parsed.map(parse).filter(lambda x:pprint()
    
ssc.start()  
ssc.awaitTermination()

-------------------------------------------
Time: 2018-01-21 20:54:51
-------------------------------------------

-------------------------------------------
Time: 2018-01-21 20:54:51
-------------------------------------------

Py4JJavaError: An error occurred while calling o32.awaitTermination.
: org.apache.spark.SparkException: An exception was raised by Python:
Traceback (most recent call last):
  File "/usr/spark-2.0.0/python/pyspark/streaming/util.py", line 65, in call
    r = self.func(t, *rdds)
  File "/usr/spark-2.0.0/python/pyspark/streaming/dstream.py", line 171, in takeAndPrint
    taken = rdd.take(num + 1)
  File "/usr/spark-2.0.0/python/pyspark/rdd.py", line 1310, in take
    res = self.context.runJob(self, takeUpToNumLeft, p)
  File "/usr/spark-2.0.0/python/pyspark/context.py", line 941, in runJob
    port = self._jvm.PythonRDD.runJob(self._jsc.sc(), mappedRDD._jrdd, partitions)
  File "/usr/spark-2.0.0/python/lib/py4j-0.10.1-src.zip/py4j/java_gateway.py", line 933, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/usr/spark-2.0.0/python/pyspark/sql/utils.py", line 63, in deco
    return f(*a, **kw)
  File "/usr/spark-2.0.0/python/lib/py4j-0.10.1-src.zip/py4j/protocol.py", line 312, in get_return_value
    format(target_id, ".", name), value)
py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.spark.api.python.PythonRDD.runJob.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 6.0 failed 4 times, most recent failure: Lost task 0.3 in stage 6.0 (TID 80, 172.19.0.5): org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "/usr/spark-2.0.0/python/lib/pyspark.zip/pyspark/worker.py", line 172, in main
    process()
  File "/usr/spark-2.0.0/python/lib/pyspark.zip/pyspark/worker.py", line 167, in process
    serializer.dump_stream(func(split_index, iterator), outfile)
  File "/usr/spark-2.0.0/python/lib/pyspark.zip/pyspark/serializers.py", line 263, in dump_stream
    vs = list(itertools.islice(iterator, batch))
  File "<ipython-input-2-5a08bc46bb58>", line 29, in <lambda>
TypeError: unorderable types: str() > int()

	at org.apache.spark.api.python.PythonRunner$$anon$1.read(PythonRDD.scala:193)
	at org.apache.spark.api.python.PythonRunner$$anon$1.<init>(PythonRDD.scala:234)
	at org.apache.spark.api.python.PythonRunner.compute(PythonRDD.scala:152)
	at org.apache.spark.api.python.PythonRDD.compute(PythonRDD.scala:63)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:319)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:283)
	at org.apache.spark.api.python.PythonRDD.compute(PythonRDD.scala:63)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:319)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:283)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:70)
	at org.apache.spark.scheduler.Task.run(Task.scala:85)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:274)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1450)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1438)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1437)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1437)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:811)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:811)
	at scala.Option.foreach(Option.scala:257)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:811)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1659)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1618)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1607)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:632)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1871)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1884)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1897)
	at org.apache.spark.api.python.PythonRDD$.runJob(PythonRDD.scala:441)
	at org.apache.spark.api.python.PythonRDD.runJob(PythonRDD.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:237)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:280)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:128)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:211)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "/usr/spark-2.0.0/python/lib/pyspark.zip/pyspark/worker.py", line 172, in main
    process()
  File "/usr/spark-2.0.0/python/lib/pyspark.zip/pyspark/worker.py", line 167, in process
    serializer.dump_stream(func(split_index, iterator), outfile)
  File "/usr/spark-2.0.0/python/lib/pyspark.zip/pyspark/serializers.py", line 263, in dump_stream
    vs = list(itertools.islice(iterator, batch))
  File "<ipython-input-2-5a08bc46bb58>", line 29, in <lambda>
TypeError: unorderable types: str() > int()

	at org.apache.spark.api.python.PythonRunner$$anon$1.read(PythonRDD.scala:193)
	at org.apache.spark.api.python.PythonRunner$$anon$1.<init>(PythonRDD.scala:234)
	at org.apache.spark.api.python.PythonRunner.compute(PythonRDD.scala:152)
	at org.apache.spark.api.python.PythonRDD.compute(PythonRDD.scala:63)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:319)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:283)
	at org.apache.spark.api.python.PythonRDD.compute(PythonRDD.scala:63)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:319)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:283)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:70)
	at org.apache.spark.scheduler.Task.run(Task.scala:85)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:274)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	... 1 more


	at org.apache.spark.streaming.api.python.TransformFunction.callPythonTransformFunction(PythonDStream.scala:92)
	at org.apache.spark.streaming.api.python.TransformFunction.apply(PythonDStream.scala:75)
	at org.apache.spark.streaming.api.python.PythonDStream$$anonfun$callForeachRDD$1.apply(PythonDStream.scala:176)
	at org.apache.spark.streaming.api.python.PythonDStream$$anonfun$callForeachRDD$1.apply(PythonDStream.scala:176)
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(ForEachDStream.scala:51)
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(ForEachDStream.scala:51)
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(ForEachDStream.scala:51)
	at org.apache.spark.streaming.dstream.DStream.createRDDWithLocalProperties(DStream.scala:415)
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1.apply$mcV$sp(ForEachDStream.scala:50)
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1.apply(ForEachDStream.scala:50)
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1.apply(ForEachDStream.scala:50)
	at scala.util.Try$.apply(Try.scala:192)
	at org.apache.spark.streaming.scheduler.Job.run(Job.scala:39)
	at org.apache.spark.streaming.scheduler.JobScheduler$JobHandler$$anonfun$run$1.apply$mcV$sp(JobScheduler.scala:245)
	at org.apache.spark.streaming.scheduler.JobScheduler$JobHandler$$anonfun$run$1.apply(JobScheduler.scala:245)
	at org.apache.spark.streaming.scheduler.JobScheduler$JobHandler$$anonfun$run$1.apply(JobScheduler.scala:245)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.apache.spark.streaming.scheduler.JobScheduler$JobHandler.run(JobScheduler.scala:244)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

-------------------------------------------
Time: 2018-01-21 20:54:52
-------------------------------------------
Row(count=1, created_at='Sun Jan 21 20:54:01 +0000 2018', username='StevenLeeF')
Row(count=1, created_at='Sun Jan 21 20:54:02 +0000 2018', username='clynnred')
Row(count=1, created_at='Sun Jan 21 20:54:02 +0000 2018', username='freeagentrocks')
Row(count=1, created_at='Sun Jan 21 20:54:01 +0000 2018', username='Evcoc54')
Row(count=1, created_at='Sun Jan 21 20:54:01 +0000 2018', username='Mike94002447')
Row(count=1, created_at='Sun Jan 21 20:54:02 +0000 2018', username='sobsa')
Row(count=1, created_at='Sun Jan 21 20:54:01 +0000 2018', username='tsachgilboa')
Row(count=1, created_at='Sun Jan 21 20:54:02 +0000 2018', username='kinxbitz')
Row(count=1, created_at='Sun Jan 21 20:54:01 +0000 2018', username='DHMatt90')
Row(count=1, created_at='Sun Jan 21 20:54:02 +0000 2018', username='newyorker_nb')
...

-------------------------------------------
Time: 2018-01-21 20:54:53
-------------------------------------------
Row(count=1, created_at='Sun Jan 21 20:54:51 +0000 2018', username='susiemagoo')
Row(count=1, created_at='Sun Jan 21 20:54:51 +0000 2018', username='RufoTina')
Row(count=1, created_at='Sun Jan 21 20:54:51 +0000 2018', username='JaneDupree1')
Row(count=1, created_at='Sun Jan 21 20:54:51 +0000 2018', username='DarrellynDenver')
Row(count=1, created_at='Sun Jan 21 20:54:51 +0000 2018', username='sstampanderson')
Row(count=1, created_at='Sun Jan 21 20:54:51 +0000 2018', username='MsJayeBee')
Row(count=1, created_at='Sun Jan 21 20:54:51 +0000 2018', username='Lifelover247')
Row(count=1, created_at='Sun Jan 21 20:54:51 +0000 2018', username='Bennythesnitch')
Row(count=1, created_at='Sun Jan 21 20:54:51 +0000 2018', username='mitranaiyu')
Row(count=1, created_at='Sun Jan 21 20:54:51 +0000 2018', username='PaulConservativ')
...

-------------------------------------------
Time: 2018-01-21 20:54:54
-------------------------------------------
Row(count=1, created_at='Sun Jan 21 20:54:52 +0000 2018', username='elainesgems')
Row(count=1, created_at='Sun Jan 21 20:54:52 +0000 2018', username='shellyANN62')
Row(count=1, created_at='Sun Jan 21 20:54:52 +0000 2018', username='DemocraticShift')
Row(count=1, created_at='Sun Jan 21 20:54:52 +0000 2018', username='Bender3352')
Row(count=1, created_at='Sun Jan 21 20:54:52 +0000 2018', username='rpardo21')
Row(count=1, created_at='Sun Jan 21 20:54:52 +0000 2018', username='1057ManUp')
Row(count=1, created_at='Sun Jan 21 20:54:52 +0000 2018', username='JusPlainTalk101')
Row(count=1, created_at='Sun Jan 21 20:54:52 +0000 2018', username='somuchtodo2')
Row(count=1, created_at='Sun Jan 21 20:54:52 +0000 2018', username='iregsnikle')
Row(count=1, created_at='Sun Jan 21 20:54:52 +0000 2018', username='keithivey')
...

-------------------------------------------
Time: 2018-01-21 20:54:55
-------------------------------------------
Row(count=1, created_at='Sun Jan 21 20:54:53 +0000 2018', username='T2Rantor')
Row(count=1, created_at='Sun Jan 21 20:54:53 +0000 2018', username='bexl888')
Row(count=1, created_at='Sun Jan 21 20:54:53 +0000 2018', username='QueenbeeAxs')
Row(count=1, created_at='Sun Jan 21 20:54:53 +0000 2018', username='portie_c')
Row(count=1, created_at='Sun Jan 21 20:54:53 +0000 2018', username='attackteam1')
Row(count=1, created_at='Sun Jan 21 20:54:53 +0000 2018', username='ShawnDa44049579')
Row(count=1, created_at='Sun Jan 21 20:54:53 +0000 2018', username='CollingswoodMan')
Row(count=1, created_at='Sun Jan 21 20:54:53 +0000 2018', username='judieyoung')
Row(count=1, created_at='Sun Jan 21 20:54:53 +0000 2018', username='Rockinbear05')
[]
...

-------------------------------------------
Time: 2018-01-21 20:54:56
-------------------------------------------
Row(count=1, created_at='Sun Jan 21 20:54:54 +0000 2018', username='ljsalom2')
Row(count=1, created_at='Sun Jan 21 20:54:54 +0000 2018', username='perfectsliders')
Row(count=1, created_at='Sun Jan 21 20:54:54 +0000 2018', username='EddieBollich')
Row(count=1, created_at='Sun Jan 21 20:54:54 +0000 2018', username='EdTarzanaCoin')
Row(count=1, created_at='Sun Jan 21 20:54:54 +0000 2018', username='Bella05746310')
Row(count=1, created_at='Sun Jan 21 20:54:54 +0000 2018', username='rafardrgz')
[]
Row(count=1, created_at='Sun Jan 21 20:54:54 +0000 2018', username='uh_hey_guys')
Row(count=1, created_at='Sun Jan 21 20:54:54 +0000 2018', username='BAMBI321')
Row(count=1, created_at='Sun Jan 21 20:54:54 +0000 2018', username='bishopjane10')
...

-------------------------------------------
Time: 2018-01-21 20:54:57
-------------------------------------------
Row(count=1, created_at='Sun Jan 21 20:54:55 +0000 2018', username='Spacebunnyday')
Row(count=1, created_at='Sun Jan 21 20:54:55 +0000 2018', username='LuanaMacLac')
Row(count=1, created_at='Sun Jan 21 20:54:55 +0000 2018', username='YankeefanAJO')
Row(count=1, created_at='Sun Jan 21 20:54:55 +0000 2018', username='MarkLaw404')
Row(count=1, created_at='Sun Jan 21 20:54:55 +0000 2018', username='SouthSideChiJoe')
Row(count=1, created_at='Sun Jan 21 20:54:55 +0000 2018', username='jadvszaros')
Row(count=1, created_at='Sun Jan 21 20:54:55 +0000 2018', username='JanBuffum')
Row(count=1, created_at='Sun Jan 21 20:54:55 +0000 2018', username='SnowflakesAreUs')
Row(count=1, created_at='Sun Jan 21 20:54:55 +0000 2018', username='tweet_petunia')
[]
...

-------------------------------------------
Time: 2018-01-21 20:54:58
-------------------------------------------
Row(count=1, created_at='Sun Jan 21 20:54:56 +0000 2018', username='AlaskaLadyDee')
Row(count=1, created_at='Sun Jan 21 20:54:56 +0000 2018', username='C141Starlifter1')
Row(count=1, created_at='Sun Jan 21 20:54:56 +0000 2018', username='Sue31009422')
Row(count=1, created_at='Sun Jan 21 20:54:56 +0000 2018', username='dburke32')
[]
Row(count=1, created_at='Sun Jan 21 20:54:56 +0000 2018', username='bijasi83')
Row(count=1, created_at='Sun Jan 21 20:54:56 +0000 2018', username='OorDayHasCome')
Row(count=1, created_at='Sun Jan 21 20:54:56 +0000 2018', username='UdvarhelyKevin')
Row(count=1, created_at='Sun Jan 21 20:54:56 +0000 2018', username='rayann2320')
Row(count=1, created_at='Sun Jan 21 20:54:56 +0000 2018', username='D15298364')
...

-------------------------------------------
Time: 2018-01-21 20:54:59
-------------------------------------------
Row(count=1, created_at='Sun Jan 21 20:54:57 +0000 2018', username='perfectsliders')
Row(count=1, created_at='Sun Jan 21 20:54:57 +0000 2018', username='Drtom11Richards')
Row(count=1, created_at='Sun Jan 21 20:54:57 +0000 2018', username='jr8877')
Row(count=1, created_at='Sun Jan 21 20:54:57 +0000 2018', username='cathipatpersist')
Row(count=1, created_at='Sun Jan 21 20:54:57 +0000 2018', username='yojudenz')
Row(count=1, created_at='Sun Jan 21 20:54:57 +0000 2018', username='JoshuaPStarr')
Row(count=1, created_at='Sun Jan 21 20:54:57 +0000 2018', username='lesliallenMK')
Row(count=1, created_at='Sun Jan 21 20:54:57 +0000 2018', username='nizmycuba')
Row(count=1, created_at='Sun Jan 21 20:54:57 +0000 2018', username='Hopitini')
Row(count=1, created_at='Sun Jan 21 20:54:57 +0000 2018', username='MetroDonMartin')
...

-------------------------------------------
Time: 2018-01-21 20:55:00
-------------------------------------------
Row(count=1, created_at='Sun Jan 21 20:54:58 +0000 2018', username='MemphisGrits2')
Row(count=1, created_at='Sun Jan 21 20:54:58 +0000 2018', username='HtServadac')
Row(count=1, created_at='Sun Jan 21 20:54:58 +0000 2018', username='bluebonnetbunny')
Row(count=1, created_at='Sun Jan 21 20:54:58 +0000 2018', username='Embyou')
Row(count=1, created_at='Sun Jan 21 20:54:58 +0000 2018', username='kdelaneyg')
Row(count=1, created_at='Sun Jan 21 20:54:58 +0000 2018', username='jenlgeiger1')
Row(count=1, created_at='Sun Jan 21 20:54:58 +0000 2018', username='jimdjr1522')
Row(count=1, created_at='Sun Jan 21 20:54:58 +0000 2018', username='grayan12')
Row(count=1, created_at='Sun Jan 21 20:54:58 +0000 2018', username='kbrunocrafts')
Row(count=1, created_at='Sun Jan 21 20:54:58 +0000 2018', username='jenniferpbragg')
...

-------------------------------------------
Time: 2018-01-21 20:55:01
-------------------------------------------
Row(count=1, created_at='Sun Jan 21 20:54:59 +0000 2018', username='peacecreep')
Row(count=1, created_at='Sun Jan 21 20:54:59 +0000 2018', username='KenBlac80899148')
Row(count=1, created_at='Sun Jan 21 20:54:59 +0000 2018', username='Reclusus')
Row(count=1, created_at='Sun Jan 21 20:54:59 +0000 2018', username='rauolwallenberg')
Row(count=1, created_at='Sun Jan 21 20:54:59 +0000 2018', username='Aurania101')
Row(count=1, created_at='Sun Jan 21 20:54:59 +0000 2018', username='ArtieSherman63')
Row(count=1, created_at='Sun Jan 21 20:54:59 +0000 2018', username='4HeritageMoms')
Row(count=1, created_at='Sun Jan 21 20:54:59 +0000 2018', username='Lindwall9')
Row(count=1, created_at='Sun Jan 21 20:54:59 +0000 2018', username='tedsvette')
[]
...

-------------------------------------------
Time: 2018-01-21 20:55:02
-------------------------------------------
Row(count=1, created_at='Sun Jan 21 20:55:00 +0000 2018', username='Pky77871531')
Row(count=1, created_at='Sun Jan 21 20:55:00 +0000 2018', username='parishhs2')
Row(count=1, created_at='Sun Jan 21 20:55:00 +0000 2018', username='BatCave780')
Row(count=1, created_at='Sun Jan 21 20:55:00 +0000 2018', username='kandidan')
Row(count=1, created_at='Sun Jan 21 20:55:00 +0000 2018', username='CommitConserv')
[]
Row(count=1, created_at='Sun Jan 21 20:55:00 +0000 2018', username='Pthorn6A')
[]
Row(count=1, created_at='Sun Jan 21 20:55:00 +0000 2018', username='unlv1986')
Row(count=1, created_at='Sun Jan 21 20:55:00 +0000 2018', username='matt_tappert')
...

-------------------------------------------
Time: 2018-01-21 20:55:03
-------------------------------------------
Row(count=1, created_at='Sun Jan 21 20:55:01 +0000 2018', username='FugenaAlaska')
Row(count=1, created_at='Sun Jan 21 20:55:01 +0000 2018', username='JudyElarth')
Row(count=1, created_at='Sun Jan 21 20:55:01 +0000 2018', username='mellyb_72')
Row(count=1, created_at='Sun Jan 21 20:55:01 +0000 2018', username='orthopsia')
Row(count=1, created_at='Sun Jan 21 20:55:01 +0000 2018', username='gbetree')
Row(count=1, created_at='Sun Jan 21 20:55:01 +0000 2018', username='perfectsliders')
Row(count=1, created_at='Sun Jan 21 20:55:01 +0000 2018', username='Steelpilot1')
Row(count=1, created_at='Sun Jan 21 20:55:01 +0000 2018', username='piper_low')
Row(count=1, created_at='Sun Jan 21 20:55:01 +0000 2018', username='maryfittro')
Row(count=1, created_at='Sun Jan 21 20:55:01 +0000 2018', username='EdwardLeeBoone1')
...

-------------------------------------------
Time: 2018-01-21 20:55:04
-------------------------------------------
Row(count=1, created_at='Sun Jan 21 20:55:02 +0000 2018', username='NatePetec')
Row(count=1, created_at='Sun Jan 21 20:55:02 +0000 2018', username='Kafkko')
Row(count=1, created_at='Sun Jan 21 20:55:02 +0000 2018', username='4orcedSilence')
[]
Row(count=1, created_at='Sun Jan 21 20:55:01 +0000 2018', username='sylvalucid')
Row(count=1, created_at='Sun Jan 21 20:55:02 +0000 2018', username='doolittlelady')
Row(count=1, created_at='Sun Jan 21 20:55:02 +0000 2018', username='BrennanSea')
Row(count=1, created_at='Sun Jan 21 20:55:02 +0000 2018', username='rellakat316')
Row(count=1, created_at='Sun Jan 21 20:55:02 +0000 2018', username='DEE6721')
Row(count=1, created_at='Sun Jan 21 20:55:02 +0000 2018', username='BWOTF')
...

-------------------------------------------
Time: 2018-01-21 20:55:05
-------------------------------------------
Row(count=1, created_at='Sun Jan 21 20:55:03 +0000 2018', username='cmca689489')
[]
Row(count=1, created_at='Sun Jan 21 20:55:03 +0000 2018', username='4mysources')
Row(count=1, created_at='Sun Jan 21 20:55:03 +0000 2018', username='mwskb')
Row(count=1, created_at='Sun Jan 21 20:55:03 +0000 2018', username='CovfefeM')
Row(count=1, created_at='Sun Jan 21 20:55:03 +0000 2018', username='VivianaCoelho')
Row(count=1, created_at='Sun Jan 21 20:55:03 +0000 2018', username='bill_minix')
Row(count=1, created_at='Sun Jan 21 20:55:03 +0000 2018', username='barigallup2585')
Row(count=1, created_at='Sun Jan 21 20:55:03 +0000 2018', username='Zen_of_Life')
Row(count=1, created_at='Sun Jan 21 20:55:03 +0000 2018', username='Patricia64M')
...

-------------------------------------------
Time: 2018-01-21 20:55:06
-------------------------------------------
Row(count=1, created_at='Sun Jan 21 20:55:04 +0000 2018', username='Juliet777777')
Row(count=1, created_at='Sun Jan 21 20:55:04 +0000 2018', username='tlfeathers880')
Row(count=1, created_at='Sun Jan 21 20:55:04 +0000 2018', username='yray1')
Row(count=1, created_at='Sun Jan 21 20:55:04 +0000 2018', username='Rockthevote2018')
Row(count=1, created_at='Sun Jan 21 20:55:04 +0000 2018', username='vandygal')
Row(count=1, created_at='Sun Jan 21 20:55:04 +0000 2018', username='llannerch')
[]
Row(count=1, created_at='Sun Jan 21 20:55:04 +0000 2018', username='RTMcFadyen')
Row(count=1, created_at='Sun Jan 21 20:55:04 +0000 2018', username='rulaw93')
Row(count=1, created_at='Sun Jan 21 20:55:04 +0000 2018', username='CaptainSnoop')
...

-------------------------------------------
Time: 2018-01-21 20:55:07
-------------------------------------------
Row(count=1, created_at='Sun Jan 21 20:55:05 +0000 2018', username='suenew54')
Row(count=1, created_at='Sun Jan 21 20:55:05 +0000 2018', username='BrendanBonham')
Row(count=1, created_at='Sun Jan 21 20:55:05 +0000 2018', username='YerOpinion')
Row(count=1, created_at='Sun Jan 21 20:55:05 +0000 2018', username='Angel0573')
[]
Row(count=1, created_at='Sun Jan 21 20:55:05 +0000 2018', username='pakukibakagen')
Row(count=1, created_at='Sun Jan 21 20:55:05 +0000 2018', username='dorianbraziel81')
Row(count=1, created_at='Sun Jan 21 20:55:05 +0000 2018', username='Tischindelray')
Row(count=1, created_at='Sun Jan 21 20:55:05 +0000 2018', username='puellam4')
Row(count=1, created_at='Sun Jan 21 20:55:05 +0000 2018', username='rrobbydob')
...

-------------------------------------------
Time: 2018-01-21 20:55:08
-------------------------------------------
Row(count=1, created_at='Sun Jan 21 20:55:06 +0000 2018', username='Sundaughter9')
Row(count=1, created_at='Sun Jan 21 20:55:05 +0000 2018', username='SusanOllar')
Row(count=1, created_at='Sun Jan 21 20:55:06 +0000 2018', username='kcbusiness86')
Row(count=1, created_at='Sun Jan 21 20:55:06 +0000 2018', username='fturner06144')
Row(count=1, created_at='Sun Jan 21 20:55:06 +0000 2018', username='jasanders1975')
Row(count=1, created_at='Sun Jan 21 20:55:06 +0000 2018', username='Bart_Kooij')
Row(count=1, created_at='Sun Jan 21 20:55:06 +0000 2018', username='UATV_en')
Row(count=1, created_at='Sun Jan 21 20:55:06 +0000 2018', username='yuuji_K1')
Row(count=1, created_at='Sun Jan 21 20:55:06 +0000 2018', username='kllander')
Row(count=1, created_at='Sun Jan 21 20:55:06 +0000 2018', username='lindafmanuel')
...

-------------------------------------------
Time: 2018-01-21 20:55:09
-------------------------------------------
Row(count=1, created_at='Sun Jan 21 20:55:07 +0000 2018', username='KZ40_alpha')
Row(count=1, created_at='Sun Jan 21 20:55:07 +0000 2018', username='wonder4awe')
Row(count=1, created_at='Sun Jan 21 20:55:07 +0000 2018', username='MaryAnneGruen')
Row(count=1, created_at='Sun Jan 21 20:55:07 +0000 2018', username='w_hayniebellsou')
Row(count=1, created_at='Sun Jan 21 20:55:07 +0000 2018', username='OgbijiNyiam')
Row(count=1, created_at='Sun Jan 21 20:55:07 +0000 2018', username='pmbene')
Row(count=1, created_at='Sun Jan 21 20:55:07 +0000 2018', username='MaryJan62216031')
Row(count=1, created_at='Sun Jan 21 20:55:07 +0000 2018', username='kimba1l88')
[]
Row(count=1, created_at='Sun Jan 21 20:55:07 +0000 2018', username='adrienne_mears')
...

-------------------------------------------
Time: 2018-01-21 20:55:10
-------------------------------------------
Row(count=1, created_at='Sun Jan 21 20:55:08 +0000 2018', username='B0rdertourista')
Row(count=1, created_at='Sun Jan 21 20:55:08 +0000 2018', username='I81Too')
Row(count=1, created_at='Sun Jan 21 20:55:08 +0000 2018', username='NewsInTheWorld')
Row(count=1, created_at='Sun Jan 21 20:55:08 +0000 2018', username='PeteKlein')
[]
Row(count=1, created_at='Sun Jan 21 20:55:08 +0000 2018', username='Ellen99686566')
Row(count=1, created_at='Sun Jan 21 20:55:08 +0000 2018', username='ljvantilburg')
Row(count=1, created_at='Sun Jan 21 20:55:08 +0000 2018', username='BurritosDPastor')
Row(count=1, created_at='Sun Jan 21 20:55:08 +0000 2018', username='Gagnon_11')
Row(count=1, created_at='Sun Jan 21 20:55:08 +0000 2018', username='RodolfiEd')
...

-------------------------------------------
Time: 2018-01-21 20:55:11
-------------------------------------------
Row(count=1, created_at='Sun Jan 21 20:55:09 +0000 2018', username='orthopsia')
Row(count=1, created_at='Sun Jan 21 20:55:09 +0000 2018', username='ExcobaWiz')
Row(count=1, created_at='Sun Jan 21 20:55:09 +0000 2018', username='mahrissahh')
[]
Row(count=1, created_at='Sun Jan 21 20:55:09 +0000 2018', username='GeoffTheHero')
Row(count=1, created_at='Sun Jan 21 20:55:09 +0000 2018', username='MichaelPacholek')
Row(count=1, created_at='Sun Jan 21 20:55:09 +0000 2018', username='vipscafe25')
Row(count=1, created_at='Sun Jan 21 20:55:09 +0000 2018', username='Trumpfan81')
Row(count=1, created_at='Sun Jan 21 20:55:09 +0000 2018', username='TJEstes1210')
Row(count=1, created_at='Sun Jan 21 20:55:09 +0000 2018', username='myjapanfriend')
...

-------------------------------------------
Time: 2018-01-21 20:55:12
-------------------------------------------
Row(count=1, created_at='Sun Jan 21 20:55:10 +0000 2018', username='AlexanderPThorn')
Row(count=1, created_at='Sun Jan 21 20:55:10 +0000 2018', username='nrwgnwd_cheri')
Row(count=1, created_at='Sun Jan 21 20:55:10 +0000 2018', username='Chuzzystarr')
Row(count=1, created_at='Sun Jan 21 20:55:10 +0000 2018', username='dfish875')
Row(count=1, created_at='Sun Jan 21 20:55:07 +0000 2018', username='SassyStacia1')
Row(count=1, created_at='Sun Jan 21 20:55:10 +0000 2018', username='LittellKevin')
Row(count=1, created_at='Sun Jan 21 20:55:08 +0000 2018', username='unlv1986')
Row(count=1, created_at='Sun Jan 21 20:55:10 +0000 2018', username='thomasroyn')
Row(count=1, created_at='Sun Jan 21 20:55:10 +0000 2018', username='ereilly44')
Row(count=1, created_at='Sun Jan 21 20:55:10 +0000 2018', username='dfpalmet')
...

-------------------------------------------
Time: 2018-01-21 20:55:13
-------------------------------------------
Row(count=1, created_at='Sun Jan 21 20:55:11 +0000 2018', username='LouisGilfedder')
Row(count=1, created_at='Sun Jan 21 20:55:11 +0000 2018', username='TheSaleaholic')
Row(count=1, created_at='Sun Jan 21 20:55:11 +0000 2018', username='FidelityCastro')
Row(count=1, created_at='Sun Jan 21 20:55:11 +0000 2018', username='gillianbdoll')
Row(count=1, created_at='Sun Jan 21 20:55:11 +0000 2018', username='brianbrown_')
Row(count=1, created_at='Sun Jan 21 20:55:11 +0000 2018', username='moodinale')
Row(count=1, created_at='Sun Jan 21 20:55:11 +0000 2018', username='steph93065')
Row(count=1, created_at='Sun Jan 21 20:55:11 +0000 2018', username='thislSzack')
Row(count=1, created_at='Sun Jan 21 20:55:11 +0000 2018', username='Wildcatgirl65')
Row(count=1, created_at='Sun Jan 21 20:55:11 +0000 2018', username='ptankshultz')
...

-------------------------------------------
Time: 2018-01-21 20:55:14
-------------------------------------------
Row(count=1, created_at='Sun Jan 21 20:55:12 +0000 2018', username='Artis_Elemental')
Row(count=1, created_at='Sun Jan 21 20:55:12 +0000 2018', username='Yuri_NateOn45')
Row(count=1, created_at='Sun Jan 21 20:55:12 +0000 2018', username='alliomack')
Row(count=1, created_at='Sun Jan 21 20:55:12 +0000 2018', username='manyfeathers514')
Row(count=1, created_at='Sun Jan 21 20:55:12 +0000 2018', username='MuMu4Lyfe')
Row(count=1, created_at='Sun Jan 21 20:55:12 +0000 2018', username='betsy563')
Row(count=1, created_at='Sun Jan 21 20:55:12 +0000 2018', username='stetlertd')
Row(count=1, created_at='Sun Jan 21 20:55:12 +0000 2018', username='RocksBlu')
Row(count=1, created_at='Sun Jan 21 20:55:12 +0000 2018', username='Cassanovy_K')
Row(count=1, created_at='Sun Jan 21 20:55:12 +0000 2018', username='washedboysfan')
...

-------------------------------------------
Time: 2018-01-21 20:55:15
-------------------------------------------
Row(count=1, created_at='Sun Jan 21 20:55:13 +0000 2018', username='phdlady')
Row(count=1, created_at='Sun Jan 21 20:55:13 +0000 2018', username='DanDassow')
Row(count=1, created_at='Sun Jan 21 20:55:13 +0000 2018', username='Redfigures')
Row(count=1, created_at='Sun Jan 21 20:55:13 +0000 2018', username='randombott')
Row(count=1, created_at='Sun Jan 21 20:55:13 +0000 2018', username='MattM3502')
Row(count=1, created_at='Sun Jan 21 20:55:13 +0000 2018', username='UILANI123')
Row(count=1, created_at='Sun Jan 21 20:55:13 +0000 2018', username='DebD51')
Row(count=1, created_at='Sun Jan 21 20:55:13 +0000 2018', username='LadyGemini0530')
Row(count=1, created_at='Sun Jan 21 20:55:13 +0000 2018', username='MaxBrinksie')
Row(count=1, created_at='Sun Jan 21 20:55:13 +0000 2018', username='Evf1995')
...

-------------------------------------------
Time: 2018-01-21 20:55:16
-------------------------------------------
Row(count=1, created_at='Sun Jan 21 20:55:14 +0000 2018', username='dianeth1616')
Row(count=1, created_at='Sun Jan 21 20:55:14 +0000 2018', username='AjayCnyc')
Row(count=1, created_at='Sun Jan 21 20:55:14 +0000 2018', username='RonPaulTeam')
Row(count=1, created_at='Sun Jan 21 20:55:14 +0000 2018', username='BleuZ00m')
Row(count=1, created_at='Sun Jan 21 20:55:14 +0000 2018', username='DonnaSc90833755')
Row(count=1, created_at='Sun Jan 21 20:55:14 +0000 2018', username='deenay1o')
Row(count=1, created_at='Sun Jan 21 20:55:14 +0000 2018', username='tammaroo11')
Row(count=1, created_at='Sun Jan 21 20:55:14 +0000 2018', username='booey2011')
Row(count=1, created_at='Sun Jan 21 20:55:14 +0000 2018', username='LisaMascaro')
Row(count=1, created_at='Sun Jan 21 20:55:14 +0000 2018', username='melvinroach')
...

-------------------------------------------
Time: 2018-01-21 20:55:17
-------------------------------------------
Row(count=1, created_at='Sun Jan 21 20:55:15 +0000 2018', username='katywh20')
Row(count=1, created_at='Sun Jan 21 20:55:15 +0000 2018', username='stockwell_terry')
Row(count=1, created_at='Sun Jan 21 20:55:15 +0000 2018', username='MsMandiJo')
Row(count=1, created_at='Sun Jan 21 20:55:15 +0000 2018', username='Bee30758370')
Row(count=1, created_at='Sun Jan 21 20:55:15 +0000 2018', username='Zadabee')
Row(count=1, created_at='Sun Jan 21 20:55:15 +0000 2018', username='somuchtodo2')
Row(count=1, created_at='Sun Jan 21 20:55:15 +0000 2018', username='siberiancandate')
Row(count=1, created_at='Sun Jan 21 20:55:15 +0000 2018', username='czardoz1')
Row(count=1, created_at='Sun Jan 21 20:55:15 +0000 2018', username='marlene676')
Row(count=1, created_at='Sun Jan 21 20:55:15 +0000 2018', username='StaticWyre')
...

-------------------------------------------
Time: 2018-01-21 20:55:18
-------------------------------------------
Row(count=1, created_at='Sun Jan 21 20:55:16 +0000 2018', username='rbnnrrbnnr')
Row(count=1, created_at='Sun Jan 21 20:55:16 +0000 2018', username='jamiecoleman57')
Row(count=1, created_at='Sun Jan 21 20:55:16 +0000 2018', username='bigredkitty7')
Row(count=1, created_at='Sun Jan 21 20:55:16 +0000 2018', username='MikeAE35')
Row(count=1, created_at='Sun Jan 21 20:55:16 +0000 2018', username='peggysadams')
Row(count=1, created_at='Sun Jan 21 20:55:16 +0000 2018', username='Testarosa10a')
Row(count=1, created_at='Sun Jan 21 20:55:16 +0000 2018', username='oogy')
Row(count=1, created_at='Sun Jan 21 20:55:16 +0000 2018', username='lauraMcc1422')
Row(count=1, created_at='Sun Jan 21 20:55:16 +0000 2018', username='fturner06144')
Row(count=1, created_at='Sun Jan 21 20:55:16 +0000 2018', username='LoraJanePerkin3')
...

-------------------------------------------
Time: 2018-01-21 20:55:19
-------------------------------------------
Row(count=1, created_at='Sun Jan 21 20:55:17 +0000 2018', username='barbspitz')
Row(count=1, created_at='Sun Jan 21 20:55:17 +0000 2018', username='Donna53489856')
Row(count=1, created_at='Sun Jan 21 20:55:17 +0000 2018', username='BoycottBertha')
[]
Row(count=1, created_at='Sun Jan 21 20:55:17 +0000 2018', username='justbeingme365')
Row(count=1, created_at='Sun Jan 21 20:55:17 +0000 2018', username='noropthony')
Row(count=1, created_at='Sun Jan 21 20:55:17 +0000 2018', username='beachdreamerwav')
Row(count=1, created_at='Sun Jan 21 20:55:17 +0000 2018', username='JohannaEliesje')
Row(count=1, created_at='Sun Jan 21 20:55:17 +0000 2018', username='FortinoMary')
Row(count=1, created_at='Sun Jan 21 20:55:17 +0000 2018', username='ATwre')
...

-------------------------------------------
Time: 2018-01-21 20:55:20
-------------------------------------------
Row(count=1, created_at='Sun Jan 21 20:55:18 +0000 2018', username='KBenyaala')
Row(count=1, created_at='Sun Jan 21 20:55:18 +0000 2018', username='JesseKellyDC')
Row(count=1, created_at='Sun Jan 21 20:55:18 +0000 2018', username='ArtVandelay10')
Row(count=1, created_at='Sun Jan 21 20:55:18 +0000 2018', username='AgentLP')
Row(count=1, created_at='Sun Jan 21 20:55:18 +0000 2018', username='mathers_georgia')
Row(count=1, created_at='Sun Jan 21 20:55:18 +0000 2018', username='BullHobbit')
Row(count=1, created_at='Sun Jan 21 20:55:18 +0000 2018', username='favourbia995203')
Row(count=1, created_at='Sun Jan 21 20:55:18 +0000 2018', username='lauracgilleslil')
Row(count=1, created_at='Sun Jan 21 20:55:18 +0000 2018', username='urwearingarbage')
Row(count=1, created_at='Sun Jan 21 20:55:18 +0000 2018', username='steveg1425')
...